name: run docker-compose
on: [push]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: run docker-compose
              uses: sudo-bot/action-docker-compose@latest
              with:
                  cli-args: "--version"
